### ISSUE TITLE
Chapter07 

### ISSUE THREAD

**Issue by JungHong** [PacktPublishing/Mastering-CPP-Multithreading#1]
The example code in Chapter07 does not compile.  I am using g++ version 6.4.0

dispatcher.cpp:71:19: error: ‘class Worker’ has no member named ‘getMutex’
           worker->getMutex(mtx);

**Comment by ramonberrutti** [comment]
You need to add the getter function in the header file. I'm finishing reading the book, and I open a pull request with all errors that I see.

**Comment by sonam-packt** [comment]
Please reopen the issue if still persist.
